apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbtest-deployment
  labels:
    app: lbtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbtest
  template:
    metadata:
      labels:
        app: lbtest
    spec:
      containers:
      - name: lbtest
        image: harbor.vballin.com/project1/simple-www
        imagePullPolicy: Always
        ports:
        - containerPort: 80
 ---
apiVersion: v1
kind: Service
metadata:
  name: lbtest-svc
  labels:
    app: lbtest
spec:
  ports:
    - port: 80
  selector:
    app: lbtest
  type: LoadBalancer
